name: flutter_extensionz
description: A set of Flutter extensions I use in various projects. Including BuildContext, Color extensions and more.
version: 5.1.3
repository: https://github.com/mj12358/flutter-extensionz
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - flutter
  - extension

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter
